### ISSUE TITLE
DeCONZ long release or hold commands not working

### ISSUE THREAD

**Issue by FezVrasta** [AYapejian/node-red-contrib-home-assistant#72]
**Describe the bug**
The DeCONZ events received by the remotes don't seem to work properly, I can only get "short release" (short press) events, while "long release" and "hold" seem to be flaky, I managed to trigger a long release event only once.

I'm sure it's a bug with this package because the same events work just fine if controlled using the built-in Home Assistant automation scripts.

**To Reproduce**
1. Read a `deconz_event` from the `events: all` node
2. Log all the `msg.payload.event.event` codes using debugger
3. Notice how, after long pressing the detected events are only ending with 2 (short release)

**Expected behavior**
All the deconz event should be detected

**Screenshot**
![image](https://user-images.githubusercontent.com/5382443/39883175-53da8956-5486-11e8-86cd-c9c1dac54f22.png)

**Example Flow**
```js
[
  {
    id: "e9415866.e8e818",
    type: "server-events",
    z: "20911376.3811fc",
    name: "Home Assistant",
    server: "a513c2af.8fb5c",
    x: 240,
    y: 480,
    wires: [["d064837b.5c32e"]]
  },
  {
    id: "5ed9b78f.5f6e08",
    type: "debug",
    z: "20911376.3811fc",
    name: "",
    active: true,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: "payload.event.event",
    x: 690,
    y: 480,
    wires: []
  },
  {
    id: "d064837b.5c32e",
    type: "function",
    z: "20911376.3811fc",
    name: "is deconz event",
    func:
      "if (msg.event_type === 'deconz_event') {\n    return msg\n}\nreturn null;",
    outputs: 1,
    noerr: 0,
    x: 440,
    y: 480,
    wires: [["5ed9b78f.5f6e08"]]
  },
  {
    id: "a513c2af.8fb5c",
    type: "server",
    z: "",
    name: "Home Assistant",
    url: "https://127.0.0.1:8123",
    pass: "xxxxxxx"
  }
];

```

**Environment (please complete the following information):**
 - Node Red Version: 0.18.5
 - NR Home Assistant Plugin Version: 0.3.2
 - Is Node Red running in Docker:no

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): no

**Additional context**

The below Home Assistant action works just fine, as you can see it's listening for the 2001 event (button hold)

```yml
- action:
  - data_template:
      brightness: 255
      entity_id: light.kitchen
    service: light.turn_on
  alias: Brighten to max kitchen lights
  condition: []
  id: '1519727307662'
  trigger:
  - event_data:
      event: 2001
      id: kitchen_remote
    event_type: deconz_event
    platform: event
  hide_entity: true
```
