### ISSUE TITLE
Problem calling "Call Service" twice in linked nodes

### ISSUE THREAD

**Issue by michaelblight** [AYapejian/node-red-contrib-home-assistant#82]
I'm not sure if this is a bug or not as I'm still pretty new here. If I have two 'Call Service' nodes linked together, only the first runs. In my case I'm trying to change an input_number from -1 to 1 via 0 (ie. set_value to 0 then set_value to 1). This is because I need a tri-state boolean and I go via 0 to ensure events fire even if going from 1 to 1.

I'm currently making it work by using a script that does the two steps, and then calling the script from Node Red. So the script to go 'to 1' is:

```
  - service: input_number.set_value
    data:
      value: 0
      entity_id: input_number.heater_state
  - service: input_number.set_value
    data:
      value: 1
      entity_id: input_number.heater_state

```
