### ISSUE TITLE
Change to OAuth Access Token

### ISSUE THREAD

**Issue by drobtravels** [AYapejian/node-red-contrib-home-assistant#95]
Home Assistant has a new auth system as a Release Candidate which uses oauth instead of an api password.  It will be the default in the next release `0.76`.

With the new auth system, users will see an error "Please change to use bearer token access" and node red will be unable to connect to Home Assistant.

Users will need to enable the legacy api password to allow node red to continue to work, until this is switch to use oauth

```
auth_providers:
   - type: homeassistant
  # below will be required for node red to continue to work.
   - type: legacy_api_password
```

See https://github.com/home-assistant/home-assistant/issues/15376
